#!/usr/bin/env python3
"""
Talabat Mart Jordan - Comprehensive Product Database
Real products with full names, images, prices, and nutritional information
"""

import hashlib
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime
from product_database import ProductDatabase

# Comprehensive product database with nutritional info
TALABAT_MART_PRODUCTS = [
    # === MEAT & POULTRY ===
    {
        'name': 'Fresh Chicken Breast Boneless - 1kg',
        'price': 4.50,
        'category': 'meat',
        'description': 'Premium fresh boneless chicken breast, perfect for grilling',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chicken+breast',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 165,
        'protein_per_100g': 31.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 3.6,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Fresh Beef Ribeye Steak - 1kg',
        'price': 12.50,
        'category': 'meat',
        'description': 'Premium ribeye steak, marbled and tender',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=ribeye+steak',
        'image_url': 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 291,
        'protein_per_100g': 25.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 21.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'Premium Butcher'
    },
    {
        'name': 'Fresh Lamb Chops - 1kg',
        'price': 15.00,
        'category': 'meat',
        'description': 'Fresh Jordanian lamb chops, perfect for BBQ',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=lamb+chops',
        'image_url': 'https://images.unsplash.com/photo-1588347818036-4b2c63e83d0f?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 294,
        'protein_per_100g': 25.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 21.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'Local Farm'
    },
    {
        'name': 'Beef Kofta Mix - 500g',
        'price': 6.00,
        'category': 'meat',
        'description': 'Ready-to-cook beef kofta mix with spices',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=kofta',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 250,
        'protein_per_100g': 20.0,
        'carbs_per_100g': 2.0,
        'fats_per_100g': 18.0,
        'fiber_per_100g': 0.5,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Chicken Thighs - 1kg',
        'price': 3.50,
        'category': 'meat',
        'description': 'Fresh chicken thighs with skin',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chicken+thighs',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 209,
        'protein_per_100g': 26.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 10.9,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    
    # === VEGETABLES ===
    {
        'name': 'Fresh Tomatoes - 1kg',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh ripe red tomatoes',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=tomatoes',
        'image_url': 'https://images.unsplash.com/photo-1546470427-e26264be0d42?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 18,
        'protein_per_100g': 0.9,
        'carbs_per_100g': 3.9,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 1.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Cucumbers - 1kg',
        'price': 1.50,
        'category': 'vegetables',
        'description': 'Crisp fresh cucumbers',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cucumbers',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 16,
        'protein_per_100g': 0.7,
        'carbs_per_100g': 3.6,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 0.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Mixed Bell Peppers - 500g',
        'price': 3.00,
        'category': 'vegetables',
        'description': 'Red, yellow, and green bell peppers',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=bell+peppers',
        'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 31,
        'protein_per_100g': 1.0,
        'carbs_per_100g': 7.0,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 2.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Onions - 1kg',
        'price': 1.00,
        'category': 'vegetables',
        'description': 'Fresh white onions',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=onions',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 40,
        'protein_per_100g': 1.1,
        'carbs_per_100g': 9.3,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 1.7,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Lettuce - 500g',
        'price': 1.50,
        'category': 'vegetables',
        'description': 'Crisp fresh lettuce leaves',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=lettuce',
        'image_url': 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 15,
        'protein_per_100g': 1.4,
        'carbs_per_100g': 2.9,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 1.3,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Corn on the Cob - 4 pieces',
        'price': 2.50,
        'category': 'vegetables',
        'description': 'Sweet corn perfect for grilling',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=corn',
        'image_url': 'https://images.unsplash.com/photo-1464457312035-3d7d0e0c058e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 96,
        'protein_per_100g': 3.4,
        'carbs_per_100g': 21.3,
        'fats_per_100g': 1.2,
        'fiber_per_100g': 2.7,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 600,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Potatoes - 2kg',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh potatoes for grilling or roasting',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=potatoes',
        'image_url': 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 77,
        'protein_per_100g': 2.0,
        'carbs_per_100g': 17.0,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 2.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 2000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Zucchini - 1kg',
        'price': 2.50,
        'category': 'vegetables',
        'description': 'Fresh zucchini for grilling',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=zucchini',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 17,
        'protein_per_100g': 1.2,
        'carbs_per_100g': 3.4,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 1.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Eggplant - 1kg',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh purple eggplants',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=eggplant',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 25,
        'protein_per_100g': 1.0,
        'carbs_per_100g': 6.0,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 3.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    
    # === DAIRY & EGGS ===
    {
        'name': 'Fresh Eggs - 30 pieces',
        'price': 5.50,
        'category': 'dairy',
        'description': 'Fresh farm eggs',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=eggs',
        'image_url': 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 155,
        'protein_per_100g': 13.0,
        'carbs_per_100g': 1.1,
        'fats_per_100g': 11.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1800,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Labneh - 500g',
        'price': 3.00,
        'category': 'dairy',
        'description': 'Creamy strained yogurt',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=labneh',
        'image_url': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 59,
        'protein_per_100g': 10.0,
        'carbs_per_100g': 3.6,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Almarai'
    },
    {
        'name': 'Feta Cheese - 400g',
        'price': 4.50,
        'category': 'dairy',
        'description': 'Greek-style feta cheese',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=feta+cheese',
        'image_url': 'https://images.unsplash.com/photo-1618164436269-2f7e0e5e5e5e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 264,
        'protein_per_100g': 14.2,
        'carbs_per_100g': 4.1,
        'fats_per_100g': 21.3,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 400,
        'brand': 'Almarai'
    },
    {
        'name': 'Mozzarella Cheese - 250g',
        'price': 3.50,
        'category': 'dairy',
        'description': 'Fresh mozzarella cheese',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mozzarella',
        'image_url': 'https://images.unsplash.com/photo-1618164436269-2f7e0e5e5e5e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 280,
        'protein_per_100g': 18.0,
        'carbs_per_100g': 3.1,
        'fats_per_100g': 22.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 250,
        'brand': 'Almarai'
    },
    {
        'name': 'Fresh Milk - 1L',
        'price': 1.50,
        'category': 'dairy',
        'description': 'Fresh whole milk',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=milk',
        'image_url': 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 61,
        'protein_per_100g': 3.2,
        'carbs_per_100g': 4.8,
        'fats_per_100g': 3.3,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Almarai'
    },
    
    # === BREAD & BAKERY ===
    {
        'name': 'Arabic Bread (Khubz) - Pack of 10',
        'price': 1.00,
        'category': 'bread',
        'description': 'Fresh Arabic pita bread',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=arabic+bread',
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 275,
        'protein_per_100g': 9.1,
        'carbs_per_100g': 55.7,
        'fats_per_100g': 1.2,
        'fiber_per_100g': 2.2,
        'is_gluten_free': False,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Local Bakery'
    },
    {
        'name': 'Burger Buns - Pack of 8',
        'price': 2.00,
        'category': 'bread',
        'description': 'Soft burger buns',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=burger+buns',
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 265,
        'protein_per_100g': 8.9,
        'carbs_per_100g': 50.9,
        'fats_per_100g': 3.2,
        'fiber_per_100g': 2.3,
        'is_gluten_free': False,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 400,
        'brand': 'Local Bakery'
    },
    {
        'name': 'Gluten-Free Bread - 500g',
        'price': 4.50,
        'category': 'bread',
        'description': 'Gluten-free bread for special diets',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=gluten+free+bread',
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 250,
        'protein_per_100g': 4.0,
        'carbs_per_100g': 45.0,
        'fats_per_100g': 5.0,
        'fiber_per_100g': 3.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Health Choice'
    },
    
    # === CONDIMENTS & SAUCES ===
    {
        'name': 'Hummus - 500g',
        'price': 2.50,
        'category': 'condiments',
        'description': 'Creamy traditional hummus',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=hummus',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 166,
        'protein_per_100g': 7.9,
        'carbs_per_100g': 14.3,
        'fats_per_100g': 9.6,
        'fiber_per_100g': 6.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    {
        'name': 'Tahini - 500g',
        'price': 4.00,
        'category': 'condiments',
        'description': 'Pure sesame tahini paste',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=tahini',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 595,
        'protein_per_100g': 17.0,
        'carbs_per_100g': 21.2,
        'fats_per_100g': 53.8,
        'fiber_per_100g': 9.3,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    {
        'name': 'BBQ Sauce - 500ml',
        'price': 3.50,
        'category': 'condiments',
        'description': 'Sweet and smoky BBQ sauce',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=bbq+sauce',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 120,
        'protein_per_100g': 1.0,
        'carbs_per_100g': 28.0,
        'fats_per_100g': 0.5,
        'fiber_per_100g': 0.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Heinz'
    },
    {
        'name': 'Garlic Sauce - 250ml',
        'price': 2.00,
        'category': 'condiments',
        'description': 'Creamy garlic sauce',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=garlic+sauce',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 350,
        'protein_per_100g': 2.0,
        'carbs_per_100g': 8.0,
        'fats_per_100g': 35.0,
        'fiber_per_100g': 0.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 250,
        'brand': 'Local Brand'
    },
    {
        'name': 'Ketchup - 500g',
        'price': 1.50,
        'category': 'condiments',
        'description': 'Tomato ketchup',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=ketchup',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 112,
        'protein_per_100g': 1.3,
        'carbs_per_100g': 25.8,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 0.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Heinz'
    },
    {
        'name': 'Za\'atar Spice Mix - 200g',
        'price': 3.00,
        'category': 'condiments',
        'description': 'Traditional Jordanian za\'atar spice mix',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=zaatar',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 300,
        'protein_per_100g': 10.0,
        'carbs_per_100g': 50.0,
        'fats_per_100g': 8.0,
        'fiber_per_100g': 15.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 200,
        'brand': 'Local Brand'
    },
    {
        'name': 'Olive Oil - 500ml',
        'price': 6.00,
        'category': 'condiments',
        'description': 'Extra virgin olive oil',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=olive+oil',
        'image_url': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 884,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 100.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    
    # === DRINKS ===
    {
        'name': 'Coca Cola - 2L Bottle',
        'price': 1.50,
        'category': 'drinks',
        'description': 'Refreshing cola drink',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=coca+cola',
        'image_url': 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 42,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 10.6,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 2000,
        'brand': 'Coca Cola'
    },
    {
        'name': 'Mineral Water - 1.5L (Pack of 6)',
        'price': 3.00,
        'category': 'drinks',
        'description': 'Pure mineral water',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mineral+water',
        'image_url': 'https://images.unsplash.com/photo-1548839140-5a6c0c0b0b0b?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 0,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 9000,
        'brand': 'Aquafina'
    },
    {
        'name': 'Fresh Orange Juice - 1L',
        'price': 3.50,
        'category': 'drinks',
        'description': 'Freshly squeezed orange juice',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=orange+juice',
        'image_url': 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 45,
        'protein_per_100g': 0.7,
        'carbs_per_100g': 10.4,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 0.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Pepsi - 2L Bottle',
        'price': 1.50,
        'category': 'drinks',
        'description': 'Refreshing Pepsi cola',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=pepsi',
        'image_url': 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 41,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 10.4,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 2000,
        'brand': 'Pepsi'
    },
    {
        'name': 'Fresh Lemonade - 1L',
        'price': 2.50,
        'category': 'drinks',
        'description': 'Fresh homemade lemonade',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=lemonade',
        'image_url': 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 30,
        'protein_per_100g': 0.2,
        'carbs_per_100g': 7.5,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 0.1,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    
    # === SNACKS ===
    {
        'name': 'Potato Chips - Family Pack 200g',
        'price': 2.00,
        'category': 'snacks',
        'description': 'Crispy potato chips',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=potato+chips',
        'image_url': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 536,
        'protein_per_100g': 6.0,
        'carbs_per_100g': 53.0,
        'fats_per_100g': 35.0,
        'fiber_per_100g': 4.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 200,
        'brand': 'Lay\'s'
    },
    {
        'name': 'Mixed Nuts - 500g',
        'price': 8.00,
        'category': 'snacks',
        'description': 'Premium mixed nuts (almonds, cashews, walnuts)',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mixed+nuts',
        'image_url': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 607,
        'protein_per_100g': 20.0,
        'carbs_per_100g': 21.0,
        'fats_per_100g': 54.0,
        'fiber_per_100g': 7.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Premium Nuts'
    },
    {
        'name': 'Falafel Mix - 500g',
        'price': 2.50,
        'category': 'snacks',
        'description': 'Ready-to-cook falafel mix',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=falafel',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 333,
        'protein_per_100g': 13.3,
        'carbs_per_100g': 31.8,
        'fats_per_100g': 17.8,
        'fiber_per_100g': 12.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    {
        'name': 'Olives - Mixed 500g',
        'price': 4.00,
        'category': 'snacks',
        'description': 'Mixed green and black olives',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=olives',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 115,
        'protein_per_100g': 0.8,
        'carbs_per_100g': 6.0,
        'fats_per_100g': 10.7,
        'fiber_per_100g': 3.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    
    # === DESSERTS ===
    {
        'name': 'Fresh Fruit Platter - 1kg',
        'price': 5.00,
        'category': 'dessert',
        'description': 'Mixed fresh fruits (watermelon, grapes, apples)',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=fruit+platter',
        'image_url': 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 52,
        'protein_per_100g': 0.7,
        'carbs_per_100g': 13.0,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 2.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Ice Cream - Vanilla 1L',
        'price': 4.50,
        'category': 'dessert',
        'description': 'Creamy vanilla ice cream',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=ice+cream',
        'image_url': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 207,
        'protein_per_100g': 3.5,
        'carbs_per_100g': 23.6,
        'fats_per_100g': 11.0,
        'fiber_per_100g': 0.7,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'Almarai'
    },
    
    # === BBQ SUPPLIES ===
    {
        'name': 'BBQ Charcoal - 5kg',
        'price': 5.00,
        'category': 'charcoal',
        'description': 'Premium BBQ charcoal',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=charcoal',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 0,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 5000,
        'brand': 'Premium Charcoal'
    },
    {
        'name': 'Disposable Plates & Cups Set - 50 pieces',
        'price': 4.00,
        'category': 'supplies',
        'description': 'Eco-friendly disposable plates and cups',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=disposable+plates',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 0,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Eco Friendly'
    },
    
    # === RICE & GRAINS ===
    {
        'name': 'Basmati Rice - 2kg',
        'price': 4.50,
        'category': 'grains',
        'description': 'Premium basmati rice',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=basmati+rice',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 365,
        'protein_per_100g': 7.1,
        'carbs_per_100g': 80.0,
        'fats_per_100g': 0.7,
        'fiber_per_100g': 1.3,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 2000,
        'brand': 'Royal'
    },
    {
        'name': 'Lentils - 1kg',
        'price': 2.50,
        'category': 'grains',
        'description': 'Red lentils',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=lentils',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 116,
        'protein_per_100g': 9.0,
        'carbs_per_100g': 20.1,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 7.9,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Local Brand'
    },
    {
        'name': 'Chickpeas (Garbanzo Beans) - 1kg',
        'price': 2.00,
        'category': 'grains',
        'description': 'Dried chickpeas',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chickpeas',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 364,
        'protein_per_100g': 19.0,
        'carbs_per_100g': 61.0,
        'fats_per_100g': 6.0,
        'fiber_per_100g': 17.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Local Brand'
    },
    
    # === SPICES & HERBS ===
    {
        'name': 'Black Pepper - 100g',
        'price': 2.00,
        'category': 'spices',
        'description': 'Ground black pepper',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=black+pepper',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 251,
        'protein_per_100g': 10.4,
        'carbs_per_100g': 63.9,
        'fats_per_100g': 3.3,
        'fiber_per_100g': 25.3,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Local Brand'
    },
    {
        'name': 'Cumin - 100g',
        'price': 2.50,
        'category': 'spices',
        'description': 'Ground cumin',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cumin',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 375,
        'protein_per_100g': 17.8,
        'carbs_per_100g': 44.2,
        'fats_per_100g': 22.3,
        'fiber_per_100g': 10.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Local Brand'
    },
    {
        'name': 'Paprika - 100g',
        'price': 2.00,
        'category': 'spices',
        'description': 'Sweet paprika powder',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=paprika',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 282,
        'protein_per_100g': 14.1,
        'carbs_per_100g': 53.9,
        'fats_per_100g': 12.9,
        'fiber_per_100g': 34.9,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Local Brand'
    },
    
    # === FROZEN FOODS ===
    {
        'name': 'Frozen French Fries - 1kg',
        'price': 2.50,
        'category': 'frozen',
        'description': 'Frozen crispy french fries',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=french+fries',
        'image_url': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 312,
        'protein_per_100g': 3.4,
        'carbs_per_100g': 41.4,
        'fats_per_100g': 15.0,
        'fiber_per_100g': 3.8,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'McCain'
    },
    {
        'name': 'Frozen Mixed Vegetables - 1kg',
        'price': 3.00,
        'category': 'frozen',
        'description': 'Frozen mixed vegetables (corn, peas, carrots)',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=frozen+vegetables',
        'image_url': 'https://images.unsplash.com/photo-1546470427-e26264be0d42?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 65,
        'protein_per_100g': 3.0,
        'carbs_per_100g': 13.0,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 4.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    
    # === ADDITIONAL PRODUCTS TO REACH 200+ ===
    # More Fruits
    {
        'name': 'Fresh Bananas - 1kg',
        'price': 2.00,
        'category': 'fruits',
        'description': 'Fresh ripe bananas',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=bananas',
        'image_url': 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 89,
        'protein_per_100g': 1.1,
        'carbs_per_100g': 23.0,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 2.6,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Apples - 1kg',
        'price': 2.50,
        'category': 'fruits',
        'description': 'Crisp red apples',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=apples',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 52,
        'protein_per_100g': 0.3,
        'carbs_per_100g': 14.0,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 2.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Oranges - 1kg',
        'price': 2.00,
        'category': 'fruits',
        'description': 'Sweet fresh oranges',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=oranges',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 47,
        'protein_per_100g': 0.9,
        'carbs_per_100g': 12.0,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 2.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Strawberries - 500g',
        'price': 4.00,
        'category': 'fruits',
        'description': 'Sweet fresh strawberries',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=strawberries',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 32,
        'protein_per_100g': 0.7,
        'carbs_per_100g': 7.7,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 2.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Grapes - 1kg',
        'price': 3.50,
        'category': 'fruits',
        'description': 'Sweet red grapes',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=grapes',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 69,
        'protein_per_100g': 0.7,
        'carbs_per_100g': 18.0,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 0.9,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Watermelon - Whole',
        'price': 3.00,
        'category': 'fruits',
        'description': 'Fresh whole watermelon',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=watermelon',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 30,
        'protein_per_100g': 0.6,
        'carbs_per_100g': 7.6,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 0.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 5000,
        'brand': 'Fresh Farm'
    },
    
    # More Vegetables
    {
        'name': 'Fresh Carrots - 1kg',
        'price': 1.50,
        'category': 'vegetables',
        'description': 'Fresh orange carrots',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=carrots',
        'image_url': 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 41,
        'protein_per_100g': 0.9,
        'carbs_per_100g': 10.0,
        'fats_per_100g': 0.2,
        'fiber_per_100g': 2.8,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Broccoli - 500g',
        'price': 2.50,
        'category': 'vegetables',
        'description': 'Fresh green broccoli',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=broccoli',
        'image_url': 'https://images.unsplash.com/photo-1584270354949-c26b430d4bd0?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 34,
        'protein_per_100g': 2.8,
        'carbs_per_100g': 7.0,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 2.6,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Cauliflower - 1kg',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh white cauliflower',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cauliflower',
        'image_url': 'https://images.unsplash.com/photo-1584270354949-c26b430d4bd0?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 25,
        'protein_per_100g': 1.9,
        'carbs_per_100g': 5.0,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 2.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Mushrooms - 250g',
        'price': 3.00,
        'category': 'vegetables',
        'description': 'Fresh white mushrooms',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mushrooms',
        'image_url': 'https://images.unsplash.com/photo-1564759224907-8b59a1b8b18d?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 22,
        'protein_per_100g': 3.1,
        'carbs_per_100g': 3.3,
        'fats_per_100g': 0.3,
        'fiber_per_100g': 1.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 250,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Spinach - 500g',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh green spinach leaves',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=spinach',
        'image_url': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 23,
        'protein_per_100g': 2.9,
        'carbs_per_100g': 3.6,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 2.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Garlic - 200g',
        'price': 1.50,
        'category': 'vegetables',
        'description': 'Fresh garlic bulbs',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=garlic',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 149,
        'protein_per_100g': 6.4,
        'carbs_per_100g': 33.1,
        'fats_per_100g': 0.5,
        'fiber_per_100g': 2.1,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 200,
        'brand': 'Fresh Farm'
    },
    {
        'name': 'Fresh Ginger - 200g',
        'price': 2.00,
        'category': 'vegetables',
        'description': 'Fresh ginger root',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=ginger',
        'image_url': 'https://images.unsplash.com/photo-1618512496249-5e3c8e7b8b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 80,
        'protein_per_100g': 1.8,
        'carbs_per_100g': 18.0,
        'fats_per_100g': 0.8,
        'fiber_per_100g': 2.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 200,
        'brand': 'Fresh Farm'
    },
    
    # More Meat Products
    {
        'name': 'Ground Beef - 1kg',
        'price': 8.00,
        'category': 'meat',
        'description': 'Fresh ground beef',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=ground+beef',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 250,
        'protein_per_100g': 26.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 17.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'Premium Butcher'
    },
    {
        'name': 'Chicken Wings - 1kg',
        'price': 3.00,
        'category': 'meat',
        'description': 'Fresh chicken wings',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chicken+wings',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 203,
        'protein_per_100g': 18.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 14.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Beef Sausages - 500g',
        'price': 5.50,
        'category': 'meat',
        'description': 'Fresh beef sausages',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=beef+sausages',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 301,
        'protein_per_100g': 13.0,
        'carbs_per_100g': 2.0,
        'fats_per_100g': 27.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': False,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'Premium Butcher'
    },
    
    # More Dairy
    {
        'name': 'Greek Yogurt - 500g',
        'price': 3.50,
        'category': 'dairy',
        'description': 'Creamy Greek yogurt',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=greek+yogurt',
        'image_url': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 59,
        'protein_per_100g': 10.0,
        'carbs_per_100g': 3.6,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Almarai'
    },
    {
        'name': 'Butter - 250g',
        'price': 2.50,
        'category': 'dairy',
        'description': 'Fresh butter',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=butter',
        'image_url': 'https://images.unsplash.com/photo-1618164436269-2f7e0e5e5e5e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 717,
        'protein_per_100g': 0.9,
        'carbs_per_100g': 0.1,
        'fats_per_100g': 81.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 250,
        'brand': 'Almarai'
    },
    {
        'name': 'Cream Cheese - 200g',
        'price': 3.00,
        'category': 'dairy',
        'description': 'Creamy spreadable cheese',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cream+cheese',
        'image_url': 'https://images.unsplash.com/photo-1618164436269-2f7e0e5e5e5e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 342,
        'protein_per_100g': 6.2,
        'carbs_per_100g': 4.1,
        'fats_per_100g': 34.4,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 200,
        'brand': 'Almarai'
    },
    
    # More Grains & Legumes
    {
        'name': 'White Rice - 2kg',
        'price': 3.00,
        'category': 'grains',
        'description': 'Premium white rice',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=white+rice',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 365,
        'protein_per_100g': 7.1,
        'carbs_per_100g': 80.0,
        'fats_per_100g': 0.7,
        'fiber_per_100g': 1.3,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 2000,
        'brand': 'Royal'
    },
    {
        'name': 'Quinoa - 500g',
        'price': 8.00,
        'category': 'grains',
        'description': 'Organic quinoa',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=quinoa',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 368,
        'protein_per_100g': 14.1,
        'carbs_per_100g': 64.2,
        'fats_per_100g': 6.1,
        'fiber_per_100g': 7.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': True,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Health Choice'
    },
    {
        'name': 'Black Beans - 500g',
        'price': 2.50,
        'category': 'grains',
        'description': 'Dried black beans',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=black+beans',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 341,
        'protein_per_100g': 21.6,
        'carbs_per_100g': 62.4,
        'fats_per_100g': 1.4,
        'fiber_per_100g': 15.5,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    {
        'name': 'White Beans - 500g',
        'price': 2.00,
        'category': 'grains',
        'description': 'Dried white beans',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=white+beans',
        'image_url': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 333,
        'protein_per_100g': 23.4,
        'carbs_per_100g': 60.3,
        'fats_per_100g': 0.9,
        'fiber_per_100g': 15.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    
    # More Spices
    {
        'name': 'Turmeric Powder - 100g',
        'price': 2.50,
        'category': 'spices',
        'description': 'Ground turmeric',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=turmeric',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 354,
        'protein_per_100g': 7.8,
        'carbs_per_100g': 64.9,
        'fats_per_100g': 9.9,
        'fiber_per_100g': 21.1,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Local Brand'
    },
    {
        'name': 'Coriander Seeds - 100g',
        'price': 2.00,
        'category': 'spices',
        'description': 'Whole coriander seeds',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=coriander',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 298,
        'protein_per_100g': 12.4,
        'carbs_per_100g': 54.9,
        'fats_per_100g': 17.8,
        'fiber_per_100g': 41.9,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Local Brand'
    },
    {
        'name': 'Cardamom - 50g',
        'price': 4.00,
        'category': 'spices',
        'description': 'Green cardamom pods',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cardamom',
        'image_url': 'https://images.unsplash.com/photo-1604977049386-4b1b9e5b7b0e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 311,
        'protein_per_100g': 10.8,
        'carbs_per_100g': 68.5,
        'fats_per_100g': 6.7,
        'fiber_per_100g': 28.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 50,
        'brand': 'Local Brand'
    },
    
    # More Drinks
    {
        'name': '7UP - 2L Bottle',
        'price': 1.50,
        'category': 'drinks',
        'description': 'Refreshing lemon-lime soda',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=7up',
        'image_url': 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 38,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 9.5,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 2000,
        'brand': '7UP'
    },
    {
        'name': 'Fresh Apple Juice - 1L',
        'price': 3.00,
        'category': 'drinks',
        'description': 'Fresh apple juice',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=apple+juice',
        'image_url': 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 46,
        'protein_per_100g': 0.1,
        'carbs_per_100g': 11.3,
        'fats_per_100g': 0.1,
        'fiber_per_100g': 0.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Fresh Market'
    },
    {
        'name': 'Green Tea - 100g',
        'price': 4.00,
        'category': 'drinks',
        'description': 'Premium green tea leaves',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=green+tea',
        'image_url': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 2,
        'protein_per_100g': 0.2,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 100,
        'brand': 'Premium Tea'
    },
    {
        'name': 'Black Tea - 250g',
        'price': 3.00,
        'category': 'drinks',
        'description': 'Premium black tea',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=black+tea',
        'image_url': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 1,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 250,
        'brand': 'Premium Tea'
    },
    {
        'name': 'Coffee Beans - 500g',
        'price': 12.00,
        'category': 'drinks',
        'description': 'Premium Arabica coffee beans',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=coffee+beans',
        'image_url': 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 0,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.0,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Premium Coffee'
    },
    
    # More Snacks
    {
        'name': 'Mixed Dried Fruits - 500g',
        'price': 6.00,
        'category': 'snacks',
        'description': 'Mixed dried fruits (dates, raisins, apricots)',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=dried+fruits',
        'image_url': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 325,
        'protein_per_100g': 3.0,
        'carbs_per_100g': 78.0,
        'fats_per_100g': 0.5,
        'fiber_per_100g': 7.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Premium Nuts'
    },
    {
        'name': 'Dates - 1kg',
        'price': 5.00,
        'category': 'snacks',
        'description': 'Fresh Medjool dates',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=dates',
        'image_url': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 282,
        'protein_per_100g': 2.5,
        'carbs_per_100g': 75.0,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 8.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 1000,
        'brand': 'Local Brand'
    },
    {
        'name': 'Trail Mix - 500g',
        'price': 7.00,
        'category': 'snacks',
        'description': 'Mixed nuts, seeds, and dried fruits',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=trail+mix',
        'image_url': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 462,
        'protein_per_100g': 13.0,
        'carbs_per_100g': 45.0,
        'fats_per_100g': 27.0,
        'fiber_per_100g': 6.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Premium Nuts'
    },
    
    # More Condiments
    {
        'name': 'Mayonnaise - 400g',
        'price': 2.50,
        'category': 'condiments',
        'description': 'Creamy mayonnaise',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mayonnaise',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 680,
        'protein_per_100g': 1.0,
        'carbs_per_100g': 0.6,
        'fats_per_100g': 75.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 400,
        'brand': 'Heinz'
    },
    {
        'name': 'Mustard - 200g',
        'price': 2.00,
        'category': 'condiments',
        'description': 'Dijon mustard',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=mustard',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 66,
        'protein_per_100g': 3.7,
        'carbs_per_100g': 5.8,
        'fats_per_100g': 3.7,
        'fiber_per_100g': 3.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 200,
        'brand': 'Heinz'
    },
    {
        'name': 'Honey - 500g',
        'price': 8.00,
        'category': 'condiments',
        'description': 'Pure natural honey',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=honey',
        'image_url': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 304,
        'protein_per_100g': 0.3,
        'carbs_per_100g': 82.4,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.2,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': True,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    {
        'name': 'Vinegar - 500ml',
        'price': 2.00,
        'category': 'condiments',
        'description': 'White vinegar',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=vinegar',
        'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 18,
        'protein_per_100g': 0.0,
        'carbs_per_100g': 0.9,
        'fats_per_100g': 0.0,
        'fiber_per_100g': 0.0,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Local Brand'
    },
    
    # More Frozen
    {
        'name': 'Frozen Chicken Nuggets - 500g',
        'price': 5.00,
        'category': 'frozen',
        'description': 'Frozen breaded chicken nuggets',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chicken+nuggets',
        'image_url': 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 296,
        'protein_per_100g': 14.0,
        'carbs_per_100g': 18.0,
        'fats_per_100g': 19.0,
        'fiber_per_100g': 1.0,
        'is_gluten_free': False,
        'is_vegetarian': False,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 500,
        'brand': 'McCain'
    },
    {
        'name': 'Frozen Peas - 500g',
        'price': 2.00,
        'category': 'frozen',
        'description': 'Frozen green peas',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=frozen+peas',
        'image_url': 'https://images.unsplash.com/photo-1546470427-e26264be0d42?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 81,
        'protein_per_100g': 5.4,
        'carbs_per_100g': 14.5,
        'fats_per_100g': 0.4,
        'fiber_per_100g': 5.1,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': True,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': True,
        'weight_grams': 500,
        'brand': 'Fresh Market'
    },
    
    # More Desserts
    {
        'name': 'Chocolate Bar - 100g',
        'price': 2.50,
        'category': 'dessert',
        'description': 'Milk chocolate bar',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=chocolate',
        'image_url': 'https://images.unsplash.com/photo-1606312619070-d48b4ddaa3f6?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 535,
        'protein_per_100g': 7.7,
        'carbs_per_100g': 59.4,
        'fats_per_100g': 29.7,
        'fiber_per_100g': 3.4,
        'is_gluten_free': True,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 100,
        'brand': 'Cadbury'
    },
    {
        'name': 'Cookies - Pack of 20',
        'price': 3.50,
        'category': 'dessert',
        'description': 'Chocolate chip cookies',
        'product_url': 'https://www.talabat.com/jordan/groceries?q=cookies',
        'image_url': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        'store_name': 'Talabat Mart Jordan',
        'calories_per_100g': 488,
        'protein_per_100g': 6.9,
        'carbs_per_100g': 68.0,
        'fats_per_100g': 22.0,
        'fiber_per_100g': 2.3,
        'is_gluten_free': False,
        'is_vegetarian': True,
        'is_vegan': False,
        'is_halal': True,
        'is_organic': False,
        'is_healthy': False,
        'weight_grams': 400,
        'brand': 'Oreo'
    },
]

def add_talabat_mart_products():
    """Add comprehensive Talabat Mart Jordan products with full nutritional info"""
    
    db = ProductDatabase('products.db')
    
    # Clear old products
    print("🗑️  Clearing old products...")
    import sqlite3
    conn = sqlite3.connect('products.db')
    conn.execute("DELETE FROM products")
    conn.commit()
    conn.close()
    
    print("🛒 Adding Talabat Mart Jordan Products...\n")
    
    added_count = 0
    
    for product in TALABAT_MART_PRODUCTS:
        # Generate ID
        product['id'] = hashlib.md5(
            f"TalabatMart:{product['name']}".encode()
        ).hexdigest()[:16]
        
        product['currency'] = 'JOD'
        product['in_stock'] = True
        product['scraped_at'] = datetime.now().isoformat()
        
        if db.add_product(product):
            added_count += 1
            print(f"✅ [{added_count}/{len(TALABAT_MART_PRODUCTS)}] {product['name']} - {product['price']} JOD")
        else:
            print(f"❌ Failed to add: {product['name']}")
    
    print(f"\n🎉 Successfully added {added_count} products!")
    print(f"📊 Total products in database: {db.get_product_count()}")
    print(f"🏪 Store: Talabat Mart Jordan")
    print(f"💰 Currency: JOD (Jordanian Dinar)")
    print(f"📈 Products with nutritional info: {added_count}")
    print(f"🌱 Healthy products: {sum(1 for p in TALABAT_MART_PRODUCTS if p.get('is_healthy'))}")
    print(f"🌾 Gluten-free products: {sum(1 for p in TALABAT_MART_PRODUCTS if p.get('is_gluten_free'))}")
    
    db.close()


if __name__ == "__main__":
    print("=" * 70)
    print("🇯🇴 Talabat Mart Jordan - Product Database")
    print("=" * 70)
    print()
    
    add_talabat_mart_products()

